Header styled
nology-tech/local pull request #14
Opened 2023-01-06 17:12 UTC by JustinDotMorris

2023-01-06 17:16 UTC, DanForder requested changes

2023-01-06 17:16 UTC, DanForder commented on src/components/Header/Header.jsx
> +        <div className="header--logo-title">
both of these classnames are "elements" rather than "modifiers":

`header__container`
`header__logo-title`

2023-01-06 17:16 UTC, DanForder commented on src/pages/Favourites/Favourites.jsx
> +    <Layout isWithMenu={true}>
don't think you meant to delete the dropdown here?

2023-01-09 10:33 UTC, DanForder approved these changes

2023-01-09 10:45 UTC, GeorgeSwift16 approved these changes
all good with me, good work

2023-01-09 10:45 UTC, merged