creation of contact branch
nology-tech/local pull request #2
Opened 2023-01-03 11:16 UTC by ekauf

2023-01-03 16:18 UTC, DanForder requested changes

2023-01-03 16:18 UTC, DanForder commented on src/App.jsx
> +      <Route path="/Contact" element={<Contact />} />
lowercase for consistency: "/contact"

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.jsx
> +    buttonStyle = "button-contact";
contact is a modifier, so class should be "button--contact"

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.jsx
> +  return <button className={buttonStyle}>{buttonText}</button>;
add an onClick for this generic button component

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.scss
> +  padding: 10px 20px;
no pixels, use responsive units

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.scss
> +  border: solid black;
use scss variable for colours

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.scss
> +  margin-top: 10px;
use responsive units

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.scss
> +  border-radius: 25px;
use responsive units

2023-01-03 16:18 UTC, DanForder commented on src/components/button/Button.scss
> +  border: none;
remove whitespace between these lines.. you can run `npm run format` to automatically do your formatting

2023-01-03 16:18 UTC, DanForder commented on src/components/labelledInputTextField/labelledInputTextField.jsx
> +const LabelledInputTextField = ({
This is quite an extreme name, how about just `TextField` ?

2023-01-03 16:18 UTC, DanForder commented on src/components/labelledInputTextField/labelledInputTextField.jsx
> +    inputClassName = "labelled-input-text-field__input input-large";
input-large is a modifier: `labelled-input-text-field__input--large` would be the additional classname... see why it's a good idea for a shorter component name?

2023-01-03 16:18 UTC, DanForder commented on src/components/labelledInputTextField/labelledInputTextField.jsx
> +    <>
no need for a fragment here, there's only one parent element: the div

2023-01-03 16:18 UTC, DanForder commented on src/components/labelledInputTextField/labelledInputTextField.jsx
> +  uniqueInputFieldHtmlName,
this prop represents an id, so perhaps just call it `id` or `uniqueId` for simplicity

2023-01-03 16:18 UTC, DanForder commented on src/pages/Contact/Contact.jsx
> +    <>
no need for a fragment, there's only one parent element: the Layout

2023-01-03 16:18 UTC, DanForder commented on src/pages/Contact/Contact.jsx
> +        <main className="contact-container">
Using BEM in react, the parent class should be the name of the component. so this should be "contact" and everything inside it should be "contact__"

2023-01-03 16:18 UTC, DanForder commented on src/pages/Home/Home.jsx
> +// plz dont merge this file  =)
revert changes

2023-01-03 16:18 UTC, DanForder commented on src/styles/_variables.scss
> +$header-Font-Family: "Roboto";
lower-case-hyphenated

2023-01-04 10:34 UTC, DanForder requested changes

2023-01-04 10:34 UTC, DanForder commented on src/pages/Contact/Contact.jsx
> +            uniqueInputFieldName="contactName"
*uniqueId

2023-01-04 10:34 UTC, DanForder commented on src/components/TextField/TextField.test.jsx
> +  const { container } = customRender(<TextField />);
add labelheader and unique id

2023-01-04 10:34 UTC, DanForder commented on src/components/button/Button.scss
> +@use "../../styles/typography" as *;
remove typgraphy

2023-01-04 10:40 UTC, DanForder approved these changes

2023-01-04 11:08 UTC, katherinepv approved these changes

2023-01-04 11:10 UTC, merged