39 toggle for list view on home home list
nology-tech/local pull request #20
Opened 2023-01-09 21:59 UTC by JustinDotMorris

2023-01-10 10:17 UTC, DanForder requested changes
Lots of `--undefined` classnames coming through, due to the button's image always showing

2023-01-10 10:17 UTC, DanForder commented on src/components/Button/Button.jsx
> +      <img className={buttonImageName} src={buttonImgUrl} alt={buttonImgAlt} />
Not every button needs an `<img>`, so perhaps hide this if there is no `buttonImgUrl`?

2023-01-10 10:17 UTC, DanForder commented on src/components/Button/Button.scss
> +.button--image--discover-icon{
You have two classes here, but I don't think it's modifying an existing class?

`.button__discover-icon` ?

2023-01-10 10:17 UTC, DanForder commented on src/pages/Home/Home.test.jsx
> +});
Why are we testing the button in the Home test? Probably should be testing the `<Home>` component!

2023-01-11 08:52 UTC, DanForder requested changes

2023-01-11 08:52 UTC, DanForder commented on src/pages/Home/Home.test.jsx
> +  const buttononscreen = screen.getByText("List View");
if you're looking for a button, let's use `getByRole` and use the button role

2023-01-11 08:52 UTC, DanForder commented on src/components/Button/Button.scss
> +.button-plus,.button-minus{
should these be `.button--plus`, `.button--minus` ?

2023-01-11 10:12 UTC, DanForder requested changes

2023-01-11 10:12 UTC, DanForder commented on src/pages/Home/Home.jsx
> +      <Button buttonName="map-navigation button--minus" buttonText="-" />
Are these plus/minus styles being applied? I think it needs to passed through as `button-minus` and `button-plus`. the Button component adds the `--` itself

2023-01-11 10:46 UTC, DanForder approved these changes

2023-01-11 12:39 UTC, Cris2508 requested changes
Hi, 2 changes needs to be done:
1. the border size is 0.125rem;
2. the buttons should be vertical and in the same line.

2023-01-11 14:49 UTC, Cris2508 approved these changes
Hi, 2 changes needs to be done:
1. the border size is 0.125rem;
2. the buttons should be vertical and in the same line.

2023-01-11 14:49 UTC, merged