62 hamburger menu icon styling adjustment
nology-tech/local pull request #22
Opened 2023-01-10 13:57 UTC by GeorgeSwift16

2023-01-10 14:37 UTC, DanForder requested changes
- Fix tests, merge from main
- Do we not already have those SVGs? we demo-ed them today

2023-01-10 15:53 UTC, DanForder requested changes

2023-01-10 15:53 UTC, DanForder commented on src/components/Header/Header.jsx
> +  // <img src={menuIconString} alt="An icon of a menu" />
remove commented code

2023-01-10 15:53 UTC, DanForder commented on src/components/Menu/Menu.scss
> +.layout__menu {
this style should go in `layout.scss`

2023-01-10 15:53 UTC, DanForder commented on src/components/Menu/Menu.scss
> +  & > div:nth-child(even) {
does this need to be a div? use BEM if poss

2023-01-10 15:53 UTC, DanForder commented on src/components/MenuIcon/MenuIcon.scss
> +.hamburger-menu {
Block class should match the component name: `menu-icon`

2023-01-11 08:53 UTC, DanForder approved these changes

2023-01-11 09:59 UTC, Cris2508 requested changes
Hi George. could you please change the style of the hamburger menu? It needs to be rectangle and at the moment is square.

2023-01-11 11:47 UTC, Cris2508 approved these changes

2023-01-11 11:48 UTC, merged