72 home screen shows api results
nology-tech/local pull request #24
Opened 2023-01-11 11:53 UTC by katherinepv

2023-01-11 12:52 UTC, DanForder requested changes

2023-01-11 12:52 UTC, DanForder commented on src/pages/Home/Home.jsx
> +    const data = await response.json();
you should be able to call the existing `getInRadius` function in placeService which will return you the array of data

2023-01-11 12:52 UTC, DanForder commented on src/api/placeService.js
> +export const baseURL = "https://place-api.herokuapp.com/api/v1";
don't think this needs exporting

2023-01-11 12:53 UTC, DanForder commented on src/pages/Home/Home.jsx
> +    const data = await response.json();
this way, we can keep all the API requests in the one file

2023-01-12 16:29 UTC, DanForder approved these changes

2023-01-13 09:23 UTC, ekauf approved these changes

2023-01-13 09:23 UTC, merged