38 save button to business cards
nology-tech/local pull request #31
Opened 2023-01-13 14:25 UTC by GeorgeSwift16

2023-01-13 15:25 UTC, DanForder requested changes
fix merge conflicts

2023-01-14 11:40 UTC, GeorgeSwift16 commented
merged main, checked tests, checked build - ready

2023-01-16 08:47 UTC, DanForder requested changes

2023-01-16 08:47 UTC, DanForder commented on src/components/Button/Button.scss
> +.button--Remove {
lower-case-hypenated classnames

2023-01-16 08:47 UTC, DanForder commented on src/components/Card/Card.jsx
> +      buttonName = "Save";
*save

2023-01-16 08:47 UTC, DanForder commented on src/components/Card/Card.jsx
> +      buttonName = "Remove";
*remove

2023-01-16 10:32 UTC, DanForder requested changes
fix

2023-01-16 10:37 UTC, DanForder approved these changes

2023-01-16 11:49 UTC, DanForder approved these changes

2023-01-16 11:52 UTC, ekauf approved these changes

2023-01-16 11:52 UTC, merged