74 user can search by postcode
nology-tech/local pull request #32
Opened 2023-01-13 14:34 UTC by ellaellac

please review

2023-01-13 15:25 UTC, DanForder approved these changes

2023-01-13 15:51 UTC, ekauf requested changes
small change required. the location icon is too close to the border. can it be moved more to the right. refer back to the figma design.

2023-01-15 23:23 UTC, ekauf requested changes
![image](https://user-images.githubusercontent.com/117112590/212572763-693c1d49-309e-4115-9efa-9b0d986a0c3e.png)
another small appearance issue - placeholder text behind icon, can this be modified pls. see image

2023-01-15 23:48 UTC, ekauf commented
> 

also, when viewing the details on a card on both the map view and list view, the icon appears at the fron, maybe set a position/z-index for it. see image 
![image](https://user-images.githubusercontent.com/117112590/212574155-4093a5e3-4b7f-4604-b923-9c87a13b04a1.png)

2023-01-16 11:25 UTC, ekauf approved these changes

2023-01-16 11:25 UTC, merged