75 back button navigates to home page
nology-tech/local pull request #33
Opened 2023-01-13 14:36 UTC by GeorgeSwift16

2023-01-13 15:26 UTC, DanForder requested changes
why are we changing userService in a story to do with back button?

2023-01-14 11:50 UTC, GeorgeSwift16 commented
> why are we changing userService in a story to do with back button?

I am not sure whether its because: 
- I have accidentally been on the wrong branch or,
- Because the user service changes in my other pr  arent on main yet meaning this branch has those changes and main doesnt as their both from me?

2023-01-16 12:08 UTC, DanForder requested changes

2023-01-16 12:08 UTC, DanForder commented on src/components/Header/Header.jsx
> +      <Link to="/*" className="header__link--home">
think this should just be `"/"` ? else we'll get /* at the end of the URL

2023-01-16 12:15 UTC, ekauf approved these changes

2023-01-16 12:15 UTC, merged